DROP TABLE IF EXISTS TAB_EMPLOEEY;

CREATE TABLE TAB_EMPLOEEY
(
            id INT AUTO_INCREMENT PRIMARY KEY,
            first_name VARCHAR(255) NOT NULL ,
            last_name VARCHAR(255) NOT NULL ,
            email VARCHAR(255) NOT NULL,
);